document.querySelector(".conge_maternite").addEventListener("click",function(){
    document.querySelector("#text_maternite").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_marriage").addEventListener("click",function(){
    document.querySelector("#text_marriage").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_maladie").addEventListener("click",function(){
    document.querySelector("#text_maladie").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_absence").addEventListener("click",function(){
    document.querySelector("#text_absence").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_naissance").addEventListener("click",function(){
    document.querySelector("#text_naissance").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_annuel").addEventListener("click",function(){
    document.querySelector("#text_annuel").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})
document.querySelector(".conge_deces").addEventListener("click",function(){
    document.querySelector("#text_deces").style.display="grid"
    document.querySelector(".Type").style.width="550px"
    document.querySelector(".Type").style.paddingLeft="100px"
    document.querySelector(".Type").style.marginLeft="440px"
    document.querySelector(".Type").style.height="600px"
})